### ISSUE TITLE
Cosmetic suggestions

### ISSUE THREAD

**Issue by dzhoshkun** [gift-surg/SPOT-A-NeonatalRabbit#1]
Hi @SebastianoF 

As requested, I've briefly gone through the README file and below are a few hints you may want to consider.

A few corrections:

- typo in the name of KUL: "Katholische Universitat Leuve"
- "automatise" => "automate"
- "gift-SURG" => "GIFT-Surg"

Suggestions:

- the illustration is very good, however it's not clear to me how you do the "parameters tuning". I couldn't relate that easily to the provided examples. But that might be my own deficiency, maybe someone more experienced in the field will know what to do.
- esp. the wiki section references external documentation such as that of NiftyReg. Wherever applicable, consider providing hyperlinks to external resources within the wiki/examples.
- I like the conciseness of your main README. Keep it that way! The README should contain concise information with a lot of links, as different users will be looking for different things. When in doubt in terms of the structure to follow, consider checking out some standard Python libraries such as scikit-image, scikit-learn, etc.

**Comment by SebastianoF** [comment]
Thanks for the suggestions! Typos addressed. The Wiki is a work in progress and will soon have more examples. Close the issue for now, feel free to re-open in the future for further cosmetic suggestions.
